language: elixir

elixir: 
  - '1.10.3'

otp_release: '23.2'

env:
  - MIX_ENV=test

# script: mix coveralls.travis

script:
  - mix coveralls.travis
  - mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)